### ISSUE TITLE
Doesn't work in https://komunikacija.easistent.com/inbox/messages

### ISSUE THREAD

**Issue by iKramp** [fubuki-fanclub/ea-sux#2]
Because easistent developers are dumb and can't put that thing (https://komunikacija.easistent.com/inbox/messages) on the same link this extension probably doesn't recognize it as a part of easistent. also barely works with https://www.easistent.com/prehrana/dijaki, tho this time because easistent developers are dumb and can't make a normal ui that matches the rest of ea and so this extension can't do shit

**Comment by MaticBabnik** [comment]
@marwuint pls fix

**Comment by MaticBabnik** [comment]
solved in #4
