### ISSUE TITLE
skill issue 

### ISSUE THREAD

**Issue by dstuden** [fubuki-fanclub/ea-sux#3]
yes
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.tenor.com%2Fimages%2Ff211fce9a32f9ed123e1be9476b6b623%2Ftenor.gif&f=1&nofb=1

**Comment by MaticBabnik** [comment]
![Brain issue end thread](https://s3.eu-central-1.wasabisys.com/cdn.femboy.si/brain-issue1.gif)
